### ISSUE TITLE
Assignment 4 is ready for grading

### ISSUE THREAD

**Issue by khenrich** [VIS-2129-F2020/kristy_henrich-vis#4]
Hi Carole & Alex, hope you both are having a nice day. Here is my assignment 4 for submission.

HTML: https://github.com/VIS-2129-F2020/kristy_henrich-vis/blob/master/VIS-Assignment-4.html
.rmd: https://github.com/VIS-2129-F2020/kristy_henrich-vis/blob/master/VIS%20Assignment%204.Rmd

Thanks,
Kristy

**Comment by bauranov** [comment]
You've put a lot of work into this assignment, great job!

If you're still getting messages and warning in HTML, try adding this snippet at the top of your file 
knitr::opts_chunk$set(echo=TRUE, warning = FALSE, results = "hide", message = FALSE)
